apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      imagePullSecrets:
      - name: my-register
      containers:
        - name: prometheus-service
          image: athrunecho/assignment:v2.0
          env:
            - name: log
              valueFrom:
                configMapKeyRef:
                  name: log
                  key: log-level
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          
          volumeMounts:
          - name: log
            mountPath: "/config"
            readyOnly: true

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "2Gi"
          
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            sucessThreshold: 1
            timeoutSeconds: 1

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            sucessThreshold: 1
            timeoutSeconds: 1

          startupProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 30
            periodSeconds: 10
      
      volumes:
        - name: config
          configMap:
            name: log

    

