apiVersion: v1
kind: Service
metadata:
  annotations:
    app: httpserver
  labels:
    app: httpserver
  name: httpserver
  namespace: cic-system
spec:
  ports:
  - name: httpserver
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: httpserver
  type: ClusterIP
